// Mocks generated by Mockito 5.4.6 from annotations
// in review_ai/test/viewmodels/review_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i6;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:review_ai/domain/repositories/review_repository.dart' as _i2;
import 'package:review_ai/domain/usecases/generate_review_usecase.dart' as _i4;
import 'package:review_ai/services/ad_service.dart' as _i3;
import 'package:state_notifier/state_notifier.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReviewRepository_0 extends _i1.SmartFake
    implements _i2.ReviewRepository {
  _FakeReviewRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdState_1 extends _i1.SmartFake implements _i3.AdState {
  _FakeAdState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GenerateReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateReviewUseCase extends _i1.Mock
    implements _i4.GenerateReviewUseCase {
  MockGenerateReviewUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReviewRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeReviewRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ReviewRepository);

  @override
  _i5.Future<List<String>> call({
    required String? foodName,
    required double? deliveryRating,
    required double? tasteRating,
    required double? portionRating,
    required double? priceRating,
    required String? reviewStyle,
    _i6.File? foodImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #foodName: foodName,
              #deliveryRating: deliveryRating,
              #tasteRating: tasteRating,
              #portionRating: portionRating,
              #priceRating: priceRating,
              #reviewStyle: reviewStyle,
              #foodImage: foodImage,
            }),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);
}

/// A class which mocks [AdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdService extends _i1.Mock implements _i3.AdService {
  MockAdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);

  @override
  _i5.Stream<_i3.AdState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i3.AdState>.empty(),
          )
          as _i5.Stream<_i3.AdState>);

  @override
  _i3.AdState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAdState_1(this, Invocation.getter(#state)),
          )
          as _i3.AdState);

  @override
  _i3.AdState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeAdState_1(this, Invocation.getter(#debugState)),
          )
          as _i3.AdState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  set onError(_i7.ErrorListener? _onError) => super.noSuchMethod(
    Invocation.setter(#onError, _onError),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i3.AdState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> loadAd() =>
      (super.noSuchMethod(
            Invocation.method(#loadAd, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> showAdWithRetry({
    required Function? onUserEarnedReward,
    required dynamic Function(String)? onAdFailedToLoad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#showAdWithRetry, [], {
              #onUserEarnedReward: onUserEarnedReward,
              #onAdFailedToLoad: onAdFailedToLoad,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> showAd({required Function? onUserEarnedReward}) =>
      (super.noSuchMethod(
            Invocation.method(#showAd, [], {
              #onUserEarnedReward: onUserEarnedReward,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  bool updateShouldNotify(_i3.AdState? old, _i3.AdState? current) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
          )
          as bool);

  @override
  _i7.RemoveListener addListener(
    _i8.Listener<_i3.AdState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
          )
          as _i7.RemoveListener);
}
