// Mocks generated by Mockito 5.4.6 from annotations
// in review_ai/test/viewmodels/review_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:review_ai/domain/repositories/review_repository.dart' as _i2;
import 'package:review_ai/domain/usecases/generate_review_usecase.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReviewRepository_0 extends _i1.SmartFake
    implements _i2.ReviewRepository {
  _FakeReviewRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GenerateReviewUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGenerateReviewUseCase extends _i1.Mock
    implements _i3.GenerateReviewUseCase {
  MockGenerateReviewUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReviewRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeReviewRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ReviewRepository);

  @override
  _i4.Future<List<String>> call({
    required String? foodName,
    required double? deliveryRating,
    required double? tasteRating,
    required double? portionRating,
    required double? priceRating,
    required String? reviewStyle,
    _i5.File? foodImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #foodName: foodName,
              #deliveryRating: deliveryRating,
              #tasteRating: tasteRating,
              #portionRating: portionRating,
              #priceRating: priceRating,
              #reviewStyle: reviewStyle,
              #foodImage: foodImage,
            }),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);
}
