default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # Upload to Play Store
    upload_to_play_store(
      track: "internal",
      aab: "../../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
